[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "APC MC Shower Project"
version = "0.1"
readme = "README.md"
requires-python = ">=3.7"

[project.optional-dependencies]
test = [
  "pytest"
]
