on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v2
        with:
         token:  ${{ secrets.GITHUB_TOKEN }}

      - name: build output
        run: pipx run nox -s docs
        shell: /usr/bin/bash -e {0}
        env:
          GITHUB_PAGES: true

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: docs/build

  deploy:
    needs:
      - docs
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
